  redis:
    image: "redis"
  db:
   image: postgres
   environment:
    POSTGRES_HOST_AUTH_METHOD: trust
  vote:
    image: vote
    ports:
      - 5000:80
    links:
      - redis
  worker:
    image: worker-app
    links:
      - redis
      - db
  result:
    image: result-app
    ports:
      - 5001:80
    links:
      - db