  version: "3"
  services:
    redis:
      image: "redis"
    
    db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    
    vote:
      image: vote
      ports:
        - 5000:80
      
    worker:
      image: worker-app
      
    result:
      image: result-app
      ports:
        - 5001:80
      